// Login Flow
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';
export const DRAWER_STACK = 'DRAWER_STACK';
export const DRAWER_TAB= 'DRAWER_TAB';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const MYLIST_SCREEN = 'MYLIST_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const MYPURCHASE_SCREEN = 'MYPURCHASE_SCREEN';
export const DETAIL_SCREEN = 'DETAIL_SCREEN';
export const VIDEO_PLAYER_SCREEN = 'VIDEO_PLAYER_SCREEN';
export const SETTING_SCREEN = 'SETTING_SCREEN';
export const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN';
export const CONTACTUS_SCREEN = 'CONTACTUS_SCREEN';
export const FAQ_SCREEN = 'FAQ_SCREEN';
export const ABOUTUS_SCREEN = 'ABOUTUS_SCREEN';
export const TERMSANDCONDITION_SCREEN = 'TERMSANDCONDITION_SCREEN';

// BOTTOM TAB STACK
export const HOME_STACK = 'HOME_STACK'
export const SEARCH_STACK = 'SEARCH_STACK'
export const MYLIST_STACK = 'MYLIST_STACK'
export const PROFILE_STACK = 'PROFILE_STACK'
export const BOTTOM_TAB = 'BOTTOM_TAB'
export const MY_LIST = 'MY_LIST'

